# Generated by Django 3.2.9 on 2021-12-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211209_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
