name: link-check

on:
  push:
    branches:
      - "master"
    paths:
      - "docs/**"
  pull_request:
    paths:
      - "docs/**"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: lychee
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          # Check all markdown and html files in doc folder
          args: --verbose --no-progress './docs/docs/**/*.md'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
