---
name: label-context

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  run:
    runs-on: self-hosted
    steps:
      - uses: docker://cclorg/srvaroa-labeler:latest
        with:
          config_path: .github/labeler-context.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}