---
name: label-diff

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@1619680c5ac1ef360b944bb56a57587ba4aa2af8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          configuration-path: .github/labeler-paths.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}